version: '3.8'
services:
  redis:
    container_name: redis
    ports:
      - '6379:6379'
    image: 'redis'
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123 # TODO: change and move to secret
